export const SAFARI_TARGETS = [
  {
    id: 'safari-lion',
    animal: 'LION',
    emoji: '🦁',
    letter: 'L',
    sound: '/l/',
    habitat: 'Pride Rock',
    fact: 'The Lion is the king of the savanna with a magnificent mane!',
    prompt: 'Photograph the animal starting with /l/: LION!',
    speechText: 'Quick photographer! Spot and photograph the animal starting with L! The LION!',
    position: [-4.5, 1.8, -4],
  },
  {
    id: 'safari-zebra',
    animal: 'ZEBRA',
    emoji: '🦓',
    letter: 'Z',
    sound: '/z/',
    habitat: 'Watering Hole',
    fact: 'Zebras have unique black and white stripes like fingerprints!',
    prompt: 'Photograph the animal starting with /z/: ZEBRA!',
    speechText: 'Look near the water! Spot and photograph the animal starting with Z! The ZEBRA!',
    position: [4.2, 0.8, -3],
  },
  {
    id: 'safari-giraffe',
    animal: 'GIRAFFE',
    emoji: '🦒',
    letter: 'G',
    sound: '/g/',
    habitat: 'Acacia Trees',
    fact: 'Giraffes have extra long necks to eat the highest leaves!',
    prompt: 'Photograph the animal starting with /g/: GIRAFFE!',
    speechText: 'Look up high! Spot and photograph the animal starting with G! The GIRAFFE!',
    position: [1.2, 2.4, -7],
  },
  {
    id: 'safari-monkey',
    animal: 'MONKEY',
    emoji: '🐒',
    letter: 'M',
    sound: '/m/',
    habitat: 'Baobab Branch',
    fact: 'Monkeys love climbing trees and eating fresh fruits!',
    prompt: 'Photograph the animal starting with /m/: MONKEY!',
    speechText: 'Up in the branches! Spot and photograph the animal starting with M! The MONKEY!',
    position: [-2.0, 3.2, -6],
  },
  {
    id: 'safari-hippo',
    animal: 'HIPPO',
    emoji: '🦛',
    letter: 'H',
    sound: '/h/',
    habitat: 'River Bank',
    fact: 'Hippos love splashing in cool water during sunny days!',
    prompt: 'Photograph the animal starting with /h/: HIPPO!',
    speechText: 'Splashing in the water! Spot and photograph the animal starting with H! The HIPPO!',
    position: [-0.5, 0.5, -2],
  },
];

export function getSafariTarget(index = 0) {
  return SAFARI_TARGETS[index % SAFARI_TARGETS.length];
}
