"""phase 7: auth password_hash, story, reading_session_details

Revision ID: 59d6b3170f98
Revises: 580998cd9cf6
Create Date: 2026-09-08 04:53:45.542363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59d6b3170f98'
down_revision: Union[str, Sequence[str], None] = '580998cd9cf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('difficulty', sa.String(length=40), nullable=True),
    sa.Column('duration', sa.String(length=20), nullable=True),
    sa.Column('cover_emoji', sa.String(length=16), nullable=True),
    sa.Column('passage', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stories_id'), 'stories', ['id'], unique=False)
    op.create_table('reading_session_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('expected_text', sa.Text(), nullable=True),
    sa.Column('recognized_text', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('words_attempted', sa.Integer(), nullable=True),
    sa.Column('words_correct', sa.Integer(), nullable=True),
    sa.Column('omissions', sa.Integer(), nullable=True),
    sa.Column('substitutions', sa.Integer(), nullable=True),
    sa.Column('repetitions', sa.Integer(), nullable=True),
    sa.Column('hesitations', sa.Integer(), nullable=True),
    sa.Column('pronunciation_score', sa.Float(), nullable=True),
    sa.Column('fluency_score', sa.Float(), nullable=True),
    sa.Column('comprehension_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['learning_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reading_session_details_id'), 'reading_session_details', ['id'], unique=False)
    op.create_index(op.f('ix_reading_session_details_session_id'), 'reading_session_details', ['session_id'], unique=True)
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    op.drop_index(op.f('ix_reading_session_details_session_id'), table_name='reading_session_details')
    op.drop_index(op.f('ix_reading_session_details_id'), table_name='reading_session_details')
    op.drop_table('reading_session_details')
    op.drop_index(op.f('ix_stories_id'), table_name='stories')
    op.drop_table('stories')
    # ### end Alembic commands ###
